Temporary workaround: tomcat8 redirects form-auth to "//login"" instead of "/login”.
1 test is still failing:

```
  testSessionCreatedForContainerProtectedResourceIsStoredInMemcached(de.javakaffee.web.msm.integration.NonStickySessionsIntegrationTC8Test): id=CD88FE36E020759087DAB47489892C21-n1 expected:<302> but was:<200>
```