Fix tests: IAE for @Nonnull parameter 'storage' of LockingStrategy.create
Appearently `@Nonnull` annotations are evaluated now, this caused test
failures like this:

```
Dec 29, 2016 12:19:15 PM org.apache.catalina.core.StandardContext start
SEVERE: Error manager.start()
java.lang.IllegalArgumentException: Argument for @Nonnull parameter 'storage' of de/javakaffee/web/msm/LockingStrategy.create must not be null
        at de.javakaffee.web.msm.LockingStrategy.$$$reportNull$$$0(LockingStrategy.java)
        at de.javakaffee.web.msm.LockingStrategy.create(LockingStrategy.java)
        at de.javakaffee.web.msm.MemcachedSessionService.setLockingMode(MemcachedSessionService.java:1580)
        at de.javakaffee.web.msm.MemcachedSessionService.initNonStickyLockingMode(MemcachedSessionService.java:1551)
        at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:450)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:145)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.start(MemcachedBackupSessionManager.java:675)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4748)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
        at de.javakaffee.web.msm.integration.Tomcat6Builder.buildAndStart(Tomcat6Builder.java:42)
        at de.javakaffee.web.msm.integration.Tomcat6Builder.buildAndStart(Tomcat6Builder.java:36)
        at de.javakaffee.web.msm.MemcachedSessionManagerIntegrationTest.testStartMsmDisabled(MemcachedSessionManagerIntegrationTest.java:512)
```